### ISSUE TITLE
关于工具链统一路径的问题

### ISSUE THREAD

**Issue by xqyjlj** [RT-Thread/userapps#11]
`get_toolchain.py` 下载的工具链的路径默认在此项目的相对路径下，这样就造成我这样的社区开发者开发用户app时，每次都要切换工具链路径，代码交给别人编译时也要改工具路径，这十分的麻烦。如果统一了工具链路径，至少开发者拿到一份新的代码可以做到开箱即用了

**Comment by BernardXiong** [comment]
这里为了方便所以采用了相对路径，如果自己需要也可以自行更改。

**Comment by xqyjlj** [comment]
userapps 已经使用xmake进行构建，scons已经不适用了
