### ISSUE TITLE
riscv64的示例有问题，arm的Linux快速上手部分没有提供Linux运行脚本

### ISSUE THREAD

**Issue by GooTal** [RT-Thread/userapps#12]
你好，我按照[快速上手](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-smart/quick-start/qemu-linux/quickstart)的linux版介绍，尝试构建riscv64版本的用户程序，执行如下命令：
```
python get_toolchain.py riscv64
source smart-env.sh riscv64
```
![图片](https://user-images.githubusercontent.com/40800103/201879417-14d58ecd-63c6-49b0-af13-48a76486815d.png)
但是出现如下错误：
![图片](https://user-images.githubusercontent.com/40800103/201879641-d8f5e200-d040-4ad0-a3cc-2b6817be36f2.png)
通过echo $PATH命令，可以看到我的路径是正常的：
![图片](https://user-images.githubusercontent.com/40800103/201880221-31b1c654-20ca-4dd5-afcb-07aa47e5f4ba.png)
不清楚为什么会这样报错？

如果不加sudo前缀，只使用scons，会产生如下错误：
![图片](https://user-images.githubusercontent.com/40800103/201921151-15ca2c7d-f021-4855-a1e3-e0c61d39033a.png)
好像是riscv工具链有点问题？

另外，[快速上手](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-smart/quick-start/qemu-linux/quickstart)中还包含了arm的示例，这部分可以正常构建出用户态应用程序。
但是`userapps\prebuilt\qemu-vexpress-a9`目录下没有Linux平台的运行脚本。尽管我可以参考.bat文件自己写一个脚本，但还是希望能看到官方的示例和源码一致 ：）

谢谢

**Comment by chenhy0106** [comment]
1. 加上sudo，先前加上的变量符号会失效，这里不要sudo
2. 到tools目录下，使用python get_toolchain.py riscv64更新下工具链，然后再试试？

**Comment by MilesQin** [comment]
按照README，下载工具链，配置riscv64，scons构建时，也报同样的错误”can't link soft-float modules with double-float modules“。工具链更新了多次，scons仍然报这个错误

**Comment by BernardXiong** [comment]
还是和工具链相关，现在应该都更新正确了。

**Comment by LiguangZhang** [comment]
/home/liguang/program/riscv-lab/rt-thread/userapps/tools/gnu_gcc/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin/../lib/gcc/riscv64-unknown-linux-musl/10.1.0/../../../../riscv64-unknown-linux-musl/bin/ld: sdk/rt-thread/lib/risc-v/rv64/librtthread.a(rt_thread.o): in function `rt_thread_user_entry':
/home/kang/rtt/alliance/rt-smart/rtthread-smart/sdk/rt-thread/src/rt_thread.c:41: undefined reference to `__pthread_init_run'


sdk下的 sdk/rt-thread/lib/risc-v/rv64/librtthread.a 这个库有问题

**Comment by xqyjlj** [comment]
userapps 已经使用xmake进行构建，scons已经不适用了
