### ISSUE TITLE
关于移植到loongarch64的问题

### ISSUE THREAD

**Issue by GooTal** [RT-Thread/userapps#13]
我看到文件里使用musl的交叉工具链编译源码，比如riscv64-linux-musleabi-...
我希望把RT-Thread内核以及用户程序移植到loongarch架构上，但目前loongarch架构的musl交叉工具链似乎还没有。
但是有loongarch64-linux-gnu-gcc等工具链，请问能否用这种工具链替代呢？

**Comment by BernardXiong** [comment]
把rt-thread rtos移植到longarch上，用newlib gcc工具链即可。
