### ISSUE TITLE
Xmake f -a riscv64gc 提示 libpng-1.6.39.zip 下载报错问题 

### ISSUE THREAD

**Issue by jojoandgyc** [RT-Thread/userapps#57]
发现了一个很坑的问题，新系统没有装 Unzip，但是xmake也不会提示 无法解压 ，执行 Xmake f -a riscv64gc 一直提示 libpng-1.6.39.zip 下载不下来，执行 xmake g --pkg_searchdirs=/home/abc/ 设置了搜索本地目录，也识别不到，一直重复提示下载错误，
![image](https://github.com/user-attachments/assets/6309f67e-6910-4d48-81c8-988a5de155cc)
总体过程如下图
![image](https://github.com/user-attachments/assets/a1aa4327-2e07-40e5-ab0f-c3e9421a22cd)

**Comment by BernardXiong** [comment]
感谢反馈 & 提交PR。如PR已经解决了这个问题，还麻烦关闭这份issue，谢谢。

**Comment by unicornx** [comment]
Fixed by #58
